### ISSUE TITLE
The data is not being stored in a CSV file

### ISSUE THREAD

**Issue by kiefh** [mohdsanadzakirizvi/web-scraping-magic-with-scrapy-and-python#1]
The scrapy crawl command for redditbot, shopclues, techcrunch all produce an empty csv file.

**Comment by mohdsanadzakirizvi** [comment]
This is an old code so the website's html ids etc. might have changed or scrapy's api/interface could have changed too. Please feel free to follow the blog post and update the parts wherever required. 

You can create a PR with the updated code :)
